stages:
- validate
- plan
- apply

variables:
  TF_ROOT: "terraform"
  TF_VAR_aws_access_key: $AWS_ACCESS_KEY_ID
  TF_VAR_aws_secret_key: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

before_script:
- export TF_VAR_aws_access_key=$AWS_ACCESS_KEY_ID
- export TF_VAR_aws_secret_key=$AWS_SECRET_ACCESS_KEY
- cd $TF_ROOT
- terraform init -input=false

validate:
  stage: validate
  image:
    name: "hashicorp/terraform:latest"
    entrypoint: [""]
  script:
  - terraform validate

plan:
  stage: plan
  image:
    name: "hashicorp/terraform:latest"
    entrypoint: [""]
  script:
  - pwd
  - terraform plan -out=tfplan -input=false
  artifacts:
    paths:
    - terraform/tfplan

apply:
  stage: apply
  image:
    name: "hashicorp/terraform:latest"
    entrypoint: [""]
  script:
  - pwd
  - terraform apply -input=false tfplan
  when: manual
