apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sock-ingress
  namespace: sock-shop
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sock.mhnz.cloudns.ph
    secretName: sock-tls-secret
  rules:
  - host: sock.mhnz.cloudns.ph
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: 
            port:
              number: 80

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sock-tls
  namespace: sock-shop
spec:
  secretName: sock-tls-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: sock.mhnz.cloudns.ph
  dnsNames:
  - sock.mhnz.cloudns.ph


---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mhnz@gmail.com
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: nginx
